[mcp_servers.appium-mcp]
command = "npx"
disabled = false
startup_timeout_sec = 60
type = "stdio"
args = ["appium-mcp@@1.27.1"]
env = { ANDROID_HOME = "C:\\Users\\xujia\\AppData\\Local\\Android\\Sdk", CAPABILITIES_CONFIG = "D:\\workspace\\appProject\\app-auto-test\\.codex\\appium.capabilities.json" }
